/*
 * @lc app=leetcode id=389 lang=cpp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (53.67%)
 * Likes:    571
 * Dislikes: 247
 * Total Accepted:    162.6K
 * Total Submissions: 301.9K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
#include "cpp.h"
#include "extra.h"
using namespace std;

@lc code=start
class Solution {
public:
    char findTheDifference(string s, string t) {
        int t_xor = 0;
        for(char c: t)
            t_xor ^= c;
        
        int s_xor = 0;
        for(char c: s)
            s_xor ^= c;

        return s_xor ^ t_xor;
    }
};
// @lc code=end

